### ISSUE TITLE
When a player dies, the discord post shows a number, not player name

### ISSUE THREAD

**Issue by mrNateDog** [diggforbeer/valheim-bot#11]
![image](https://user-images.githubusercontent.com/91708251/170508688-71f1a07e-24ee-4b56-aedb-fd07bda377df.png)

Instead of showing "Player x has died" message displays "player ## has died"

**Comment by diggforbeer** [comment]
@mrNateDog @mikemarquez fixed this in https://github.com/diggforbeer/valheim-bot/pull/12
