### ISSUE TITLE
Find Replacement for Should and ShouldFluent

### ISSUE THREAD

**Issue by MikeyYeahYeah** [diggforbeer/valheim-bot#4]
@diggforbeer It looks like this package hasn't been updated since 2013... WOMP!

https://www.nuget.org/packages/ShouldFluent/

**Comment by MikeyYeahYeah** [comment]
Here is one potential candidate: https://fluentassertions.com/

**Comment by diggforbeer** [comment]
lol @MikeyYeahYeah I am so old I didn't realize that.
